# cellphone1_marca ="samsung"
# cellphone2_marca ="apple"
# cellphone3_marca ="hawuei"

# cellphone1_modelo ="s24"
# cellphone2_modelo ="phone15"
# cellphone3_modelo ="p30 pro"

# cellphone1_camaraF ="48mp"
# cellphone2_camaraF ="48mp"
# cellphone3_camaraF ="24mp"

# cellphone1_camaraT ="24mp"
# cellphone2_camaraT ="24mp"
# cellphone3_camaraT ="12mp"


# print(cellphone1_marca) 

class Cellphone():
    mark = "Samsung" 
    model = "s24" 
    camera = "48mp" 

cellphone1 = Cellphone()
cellphone2 = Cellphone()
cellphone3 = Cellphone()
cellphone4 = Cellphone()
print(cellphone1.camera)    